import dotenv from "dotenv";
dotenv.config({
  path: `.env${
    process.env.NODE_ENV ? `.${process.env.NODE_ENV}` : ".development"
  }`,
  quiet: true,
});

const {
  PORT,
  JWT_SECRET_KEY,
  NODE_ENV,
  RABBITMQ_URI,
  OTP_EXPIRATION,
  ENCRYPTION_KEY,
  ENCRYPTION_IV,
  MYSQL_DATABASE_NAME,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_HOST,
  MYSQL_PORT,
  REDIS_HOST,
  REDIS_PORT,
  XPRESSBEES_URL_GENERATE_SMALL_TOKEN,
  XPRESSBEES_URL_GENERATE_SMALL_USERNAME,
  XPRESSBEES_URL_GENERATE_SMALL_PASSWORD,
  XPRESSBEES_URL_GENERATE_SMALL_SECRET_KEY,
  XPRESSBEES_URL_CREATE_SHIPMENT_FORWARD,
  XPRESSBEES_URL_CANCEL_SHIPMENT_FORWARD,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
} = process.env;

export {
  PORT,
  JWT_SECRET_KEY,
  NODE_ENV,
  RABBITMQ_URI,
  OTP_EXPIRATION,
  ENCRYPTION_KEY,
  ENCRYPTION_IV,
  MYSQL_DATABASE_NAME,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_HOST,
  MYSQL_PORT,
  REDIS_HOST,
  REDIS_PORT,
  XPRESSBEES_URL_GENERATE_SMALL_TOKEN,
  XPRESSBEES_URL_GENERATE_SMALL_USERNAME,
  XPRESSBEES_URL_GENERATE_SMALL_PASSWORD,
  XPRESSBEES_URL_GENERATE_SMALL_SECRET_KEY,
  XPRESSBEES_URL_CREATE_SHIPMENT_FORWARD,
  XPRESSBEES_URL_CANCEL_SHIPMENT_FORWARD,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
};
